"""
SEABISCUIT - DeepSeek AI Executive Market Intelligence Modal Component
Renders structured quantitative research dossiers generated by DeepSeek AI.
"""

import streamlit as st
from typing import Dict, Any
from backend.deepseek_intel_engine import DeepSeekIntelEngine


def render_intel_dossier_modal(racecard: Dict[str, Any]) -> None:
    """Renders DeepSeek AI Market Intelligence dossier."""
    st.markdown("---")
    st.markdown("## 🤖 DEEPSEEK QUANTITATIVE MARKET DOSSIER")
    
    with st.spinner("DeepSeek AI analyzing orderbook microstructure & track surface deltas..."):
        engine = DeepSeekIntelEngine()
        dossier = engine.generate_race_dossier(racecard)
        
    st.markdown(f"**Model Engine**: `{dossier.get('model_used')}` | **Timestamp**: `{dossier.get('timestamp')}`")
    st.markdown("<div style='margin-bottom: 16px;'></div>", unsafe_allow_html=True)
    
    st.markdown(dossier.get("dossier_markdown", "No dossier generated."))
