"""
SEABISCUIT - Equine Orderbook & Market Depth View Component
Renders L2 order book depth generated by QuantBetSimulatorEngine.generate_order_book(),
driven by real market cap, odds, and A/E mispricing rather than fixed placeholder numbers.
"""

import streamlit as st
import pandas as pd
from typing import Dict, Any

from backend.bet_simulator_engine import QuantBetSimulatorEngine
from frontend.html_utils import compact_html


def render_orderbook_view(racecard: Dict[str, Any]) -> None:
    """Renders live Equine Orderbook & CLOB microstructure."""
    st.markdown(compact_html("""
    <div class="glass-card" style="border-top:4px solid #0F172A;padding:18px 24px;margin-bottom:18px;animation:slideInLeft 0.4s ease;">
        <h3 style="color:#0F172A;margin:0;font-weight:900;font-family:'Outfit',sans-serif;">📊 INSTITUTIONAL EQUINE ORDERBOOK &amp; CLOB MICROSTRUCTURE</h3>
        <p style="color:var(--text-muted,#64748B);margin:4px 0 0;font-size:0.88rem;font-weight:600;">
            Synthetic L2 depth: spread widens with longer odds &amp; A/E mispricing, liquidity scales with market cap.
        </p>
    </div>
    """), unsafe_allow_html=True)

    assets = racecard.get("equity_assets", [])
    if not assets:
        st.info("No orderbook data available.")
        return

    col1, col2 = st.columns([1, 2.5])

    with col1:
        st.markdown("#### Select Equine Asset:")
        selected_ticker = st.radio(
            "Runner Tickers:",
            options=[a.get("ticker") for a in assets],
            format_func=lambda x: f"{x} ({next((a.get('horse') for a in assets if a.get('ticker') == x), '')})",
            label_visibility="collapsed"
        )

    target_asset = next((a for a in assets if a.get("ticker") == selected_ticker), assets[0])
    book = QuantBetSimulatorEngine.generate_order_book(target_asset, assets)

    with col2:
        if not book:
            st.info("No orderbook data available for this runner.")
            return

        st.markdown(f"#### Orderbook Depth: `{book['ticker']}` ({book['horse']})")

        m1, m2, m3 = st.columns(3)
        m1.metric("Bid 1 / Ask 1 Spread", f"${book['spread_usd']:.2f}", delta=f"{book['spread_pct']:.2f}% of mid")
        m2.metric("Micro-Price", f"${book['micro_price']:.2f}")
        m3.metric("Order Flow Imbalance", f"{book['imbalance_pct']:+.1f}%", delta=book["imbalance_label"])

        df_bids = pd.DataFrame(book["bids"]).rename(columns={"level": "Level", "price_usd": "Price ($)", "volume_usd": "Volume ($)"})
        df_asks = pd.DataFrame(book["asks"]).rename(columns={"level": "Level", "price_usd": "Price ($)", "volume_usd": "Volume ($)"})

        b_col, a_col = st.columns(2)
        with b_col:
            st.markdown("<h5 style='color: #10B981;'>🟢 BIDS (BUY ORDERS)</h5>", unsafe_allow_html=True)
            st.dataframe(df_bids, width="stretch", hide_index=True)

        with a_col:
            st.markdown("<h5 style='color: #F43F5E;'>🔴 ASKS (SELL ORDERS)</h5>", unsafe_allow_html=True)
            st.dataframe(df_asks, width="stretch", hide_index=True)
